### PR TITLE
Removed creatation of usage plans as they are not required and were n…

### PR DESCRIPTION
**Pull request by harryslimes**
There are 3 main changes in this PR. Perhaps I should have separated them out... 

1. Removed creation of usage plan. Isn't required for functioning are we aren't cleaning up. 300 limit on usage policy

2. added modify_request_dict which allows passing in a dict that defines a request to be modified for use with the API Gateway. This change allowed me to easily implement an async scraper.

3. Project was previously ignoring query string paramaters in request if path was empty. Params are now explicitly extracted and appended to params to request object.

### CODE REVIEW

**Comment by Ge0rg3** [comment]
Thanks for this, have been meaning to remove the usage plans for a while, but stopping creation works just as well 😄 
Please can you elaborate on the modify_request_dict usage, so that I can include in README?

**Comment by harryslimes** [comment]
Maybe if I explain my use case for modify_request_dict it will make sense....

So I wanted to run the requests asynchronously. 

Normal usage of **requests-ip-rotator** involves it making the requests for you synchronously.

In my usage I use **requests-ip-rotator** to open a gateway and then I use the modify_request_dict function to transform my http requests before sending them asynchronously using a aiohttp + asyncio based solution.

Does that make sense?
If it doesn't, I could provide you with actual code.

**Comment by Ge0rg3** [comment]
Some example code would be appreciated, thanks.
In my own experience, I've used the multiprocessing library to perform async requests, but I realize that this is more intensive than an asyncio approach.

**Comment by harryslimes** [comment]
https://gist.github.com/harryslimes/a9b5e38356009e51af387e28ba6fdc24

Hopefully this makes sense.
A preferable solution would involve a properly managed connection pool where the max concurrent connections can set but the code above is quite simple to understand.

**Comment by Ge0rg3** [comment]
I'd like to apologize for the delay and thanks for the code sample! Please can you also include some example usage of the modify_request_dict functionality - some examples in the documentation would be great, but if not, I'll be happy to add them myself 😄

**Comment by vincenthawke** [comment]
Hey Harry, I am glad to see that you were thinking ahead way before I even found this wonderful module. I would really appreciate, if you could post a small usage example of your new class. It would help me understnad it far better. Thanks!

**Comment by geekCyberWarrior** [comment]
Hey Harry! This is such an wonderful idea of thinking outside the box and serve us a lot of benefit while utilising the library shared, saving us a lot of time.

You can find a usage example of this over https://gist.github.com/geekCyberWarrior/eacfeef757e5aacaef0c94e7e611f3bb

Please do fork it and leave comments which would be helpful for me as well so that I learn if I'm not right.

**Comment by xitex** [comment]
Hey Harry! Try it with requests_html module and got an error
mount() missing 1 required positional argument: 'adapter'
my code is
gateway_2 = ApiGateway("https://www.google.com",  access_key_id="hereis my id", access_key_secret="and here is secret")


# Starts new ApiGateway instances for site, or locates existing endpoints if they already exist.

# Starts new ApiGateway instances even if some already exist.
gateway_2.start(force=True)
session_2 = HTMLSession
session_2.mount("https://www.google.com", gateway_2)

Can you help with this?

**Comment by Ge0rg3** [comment]
Merging in and will add requested changes myself shortly, thanks for the PR!

**Comment by rexovas** [comment]
Why was this change removed from the main branch?

**Comment by Ge0rg3** [comment]
The usage plan and query string changes have been kept, but the asyncio was reverted as preference here is to use the `requests` lib with `concurrent.futures` threading.

**Comment by rexovas** [comment]
> The usage plan and query string changes have been kept, but the asyncio was reverted as preference here is to use the `requests` lib with `concurrent.futures` threading.

Thanks for the reply, would you be able to share a usage example?

**Comment by rexovas** [comment]
Silly question, should `futures_map[future] = i` be a dict? Seems to be an array.

In my case I have an array of tasks which are objects like such { req_id: 0, url: https://site.com }

Are futures a hashable type which can be used as a key to retrieve the input task? (that would make sense as for the logging of req_id)

would it be sufficient to simply keep futures_map as a list and append the futures to it? so 

```
futures_map = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=50) as executor:
        # Send 100 requests
        for i in range(100):
            future = executor.submit(
                scrape_site,
                f"{BASE_URL}/{i}",
                gateway
            )
            futures_map.append(future)
    
        # Catch async responses
        for future in concurrent.futures.as_completed(futures_map):
            # Handle error
            error = future.exception()
            if error:
                print(f"Error")
                continue
            # Handle success
            result = future.result()
            print(f"{result.status_code}")
```

**Comment by Ge0rg3** [comment]
Yep, you're right, futures_map should be a dict - I just wrote this code quickly as an example 👍 

With regards to the gateway being mounted to separate sessions - this is so that cookies don't get carried over between requests, otherwise you may get rate limited on this basis.

Hope all is working now!

**Pull request merged**
